In [ ]:
%cd /content

!git clone -b didem/patchtst-baseline \
https://github.com/didemneda/regime-aware-head-pruning.git

%cd /content/regime-aware-head-pruning
!git status
!git branch
!ls

/content
Cloning into 'regime-aware-head-pruning'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 25 (delta 5), reused 14 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 39.12 KiB | 667.00 KiB/s, done.
Resolving deltas: 100% (5/5), done.
/content/regime-aware-head-pruning
On branch didem/patchtst-baseline
Your branch is up to date with 'origin/didem/patchtst-baseline'.

nothing to commit, working tree clean
* didem/patchtst-baseline
01_patchtst_baseline.ipynb  README.md	      results  src
configs			    requirements.txt  scripts

In [ ]:
%cd /content

!rm -rf Time-Series-Library
!git clone https://github.com/thuml/Time-Series-Library.git

/content
Cloning into 'Time-Series-Library'...
remote: Enumerating objects: 2295, done.
remote: Total 2295 (delta 0), reused 0 (delta 0), pack-reused 2295 (from 1)
Receiving objects: 100% (2295/2295), 78.43 MiB | 30.50 MiB/s, done.
Resolving deltas: 100% (1571/1571), done.

In [ ]:
%cd /content/Time-Series-Library
!ls

/content/Time-Series-Library
CONTRIBUTING.md     Dockerfile	LICENSE  README.md	   run.py    utils
data_provider	    exp		models	 README_zh.md	   scripts
docker-compose.yml  layers	pic	 requirements.txt  tutorial

In [ ]:
%cd /content/Time-Series-Library

!pip install -q -r requirements.txt
!pip install -q statsmodels scipy scikit-learn matplotlib pyyaml thop

/content/Time-Series-Library
ERROR: Ignored the following versions that require a different python version: 0.0.11 Requires-Python <3.11,>=3.10; 0.0.12 Requires-Python <3.11,>=3.10; 0.1.1 Requires-Python <3.11,>=3.10; 0.1.14 Requires-Python <3.11,>=3.10; 0.1.15 Requires-Python <3.11,>=3.10; 0.1.16 Requires-Python <3.11,>=3.10; 0.1.17 Requires-Python <3.11,>=3.10; 0.1.18 Requires-Python <3.11,>=3.10; 0.1.2 Requires-Python <3.11,>=3.10; 0.1.21 Requires-Python <3.11,>=3.10; 0.1.22 Requires-Python <3.11,>=3.10; 0.1.23 Requires-Python <3.11,>=3.10; 0.1.24 Requires-Python <3.11,>=3.10; 0.1.25 Requires-Python <3.11,>=3.10; 0.1.3 Requires-Python <3.11,>=3.10; 0.1.31 Requires-Python <3.11,>=3.10; 0.1.32 Requires-Python <3.11,>=3.10; 0.1.4 Requires-Python <3.11,>=3.10; 0.1.5 Requires-Python <3.11,>=3.10; 0.1.6 Requires-Python <3.11,>=3.10; 0.1.7 Requires-Python <3.11,>=3.10; 0.10.0 Requires-Python >=3.7,<3.10; 0.10.1 Requires-Python >=3.7,<3.10; 0.11.0 Requires-Python >=3.7,<3.10; 0.11.1 Requires-Python >=3.7,<3.10; 0.11.2 Requires-Python >=3.7,<3.10; 0.11.3 Requires-Python >=3.7,<3.10; 0.11.4 Requires-Python >=3.7,<3.10; 0.12.0 Requires-Python >=3.7,<3.10; 0.12.1 Requires-Python >=3.7,<3.10; 0.13.0 Requires-Python >=3.7,<3.11; 0.13.1 Requires-Python >=3.7,<3.11; 0.13.2 Requires-Python >=3.7,<3.11; 0.13.3 Requires-Python >=3.7,<3.11; 0.13.4 Requires-Python >=3.7,<3.11; 0.14.0 Requires-Python >=3.7,<3.11; 0.14.1 Requires-Python <3.11,>=3.7; 0.15.0 Requires-Python <3.11,>=3.7; 0.15.1 Requires-Python <3.11,>=3.7; 0.16.0 Requires-Python <3.11,>=3.7; 0.16.1 Requires-Python <3.12,>=3.7; 0.17.0 Requires-Python <3.12,>=3.7; 0.17.1 Requires-Python <3.12,>=3.7; 0.17.2 Requires-Python <3.12,>=3.7; 0.18.0 Requires-Python <3.12,>=3.7; 0.18.1 Requires-Python <3.12,>=3.7; 0.19.0 Requires-Python <3.12,>=3.7; 0.19.1 Requires-Python <3.12,>=3.7; 0.19.2 Requires-Python <3.12,>=3.7; 0.20.0 Requires-Python <3.12,>=3.8; 0.20.1 Requires-Python <3.12,>=3.8; 0.21.0 Requires-Python <3.12,>=3.8; 0.21.1 Requires-Python <3.12,>=3.8; 0.22.0 Requires-Python <3.12,>=3.8; 0.22.1 Requires-Python <3.12,>=3.8; 0.23.0 Requires-Python <3.12,>=3.8; 0.23.1 Requires-Python <3.12,>=3.8; 1.0.1 Requires-Python <3.11,>=3.10; 1.1.0 Requires-Python <3.11,>=3.10; 1.2.0 Requires-Python <3.12,>=3.10; 1.2.1 Requires-Python <3.12,>=3.10; 1.2.2 Requires-Python <3.12,>=3.10; 1.2.3 Requires-Python <3.12,>=3.10; 1.2.4 Requires-Python <3.12,>=3.10; 1.2.5 Requires-Python <3.12,>=3.10; 1.2.6 Requires-Python <3.12,>=3.10; 1.2.7 Requires-Python <3.12,>=3.10; 1.2.8 Requires-Python <3.12,>=3.10; 1.2.9 Requires-Python <3.12,>=3.10; 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.3.0 Requires-Python <3.12,>=3.10
ERROR: Could not find a version that satisfies the requirement timesfm==1.3.0 (from versions: 1.0.0, 2.0.0, 2.0.1, 2.0.2)
ERROR: No matching distribution found for timesfm==1.3.0

In [ ]:
import torch
import pandas as pd
import numpy as np

print("Torch:", torch.__version__)
print("GPU:", torch.cuda.get_device_name(0))

Torch: 2.11.0+cu128
GPU: Tesla T4

In [ ]:
%cd /content/Time-Series-Library

!mkdir -p dataset
!rm -rf dataset/ETDataset
!git clone https://github.com/zhouhaoyi/ETDataset.git dataset/ETDataset

/content/Time-Series-Library
Cloning into 'dataset/ETDataset'...
remote: Enumerating objects: 187, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 187 (delta 26), reused 20 (delta 20), pack-reused 157 (from 1)
Receiving objects: 100% (187/187), 3.86 MiB | 7.30 MiB/s, done.
Resolving deltas: 100% (62/62), done.

In [ ]:
from pathlib import Path

data_path = Path(
    "/content/Time-Series-Library/dataset/ETDataset/ETT-small/ETTh1.csv"
)

print("Dosya var mı:", data_path.exists())
print(data_path)

Dosya var mı: True
/content/Time-Series-Library/dataset/ETDataset/ETT-small/ETTh1.csv

In [ ]:
import pandas as pd

df = pd.read_csv(data_path)

print("Boyut:", df.shape)
display(df.head())

print("Kolonlar:", df.columns.tolist())
print("Eksik değer sayıları:")
print(df.isna().sum())

Boyut: (17420, 8)

                  date   HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
0  2016-07-01 00:00:00  5.827  2.009  1.599  0.462  4.203  1.340  30.531000
1  2016-07-01 01:00:00  5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2  2016-07-01 02:00:00  5.157  1.741  1.279  0.355  3.777  1.218  27.787001
3  2016-07-01 03:00:00  5.090  1.942  1.279  0.391  3.807  1.279  25.044001
4  2016-07-01 04:00:00  5.358  1.942  1.492  0.462  3.868  1.279  21.948000

Kolonlar: ['date', 'HUFL', 'HULL', 'MUFL', 'MULL', 'LUFL', 'LULL', 'OT']
Eksik değer sayıları:
date    0
HUFL    0
HULL    0
MUFL    0
MULL    0
LUFL    0
LULL    0
OT      0
dtype: int64

In [ ]:
!pip install -q --no-deps einops
!pip install -q --no-deps patool
!pip install -q --no-deps thop
!pip install -q --no-deps sktime
!pip install -q reformer-pytorch
!pip install -q --no-deps scikit-base

In [ ]:
import torch
import numpy as np
import pandas as pd
import scipy
import sklearn
import statsmodels
import einops
import patoolib



from models import PatchTST

print("PatchTST import başarılı.")
print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())

PatchTST import başarılı.
Torch: 2.11.0+cu128
CUDA: True

In [ ]:
%cd /content/Time-Series-Library

!python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_336_96_baseline \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 4 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des baseline \
  --itr 1

/content/Time-Series-Library
Using GPU
Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1
  Model ID:           ETTh1_336_96_baselineModel:              PatchTST

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETDataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M
  Target:             OT                  Freq:               h
  Checkpoints:        ./checkpoints/

Forecasting Task
  Seq Len:            336                 Label Len:          48
  Pred Len:           96                  Seasonal Patterns:  Monthly
  Inverse:            0

Model Parameters
  Top k:              5                   Num Kernels:        6
  Enc In:             7                   Dec In:             7
  C Out:              7                   d model:            128
  n heads:            4                   e layers:           3
  d layers:           1                   d FF:               256
  Moving Avg:         25                  Factor:             3
  Distil:             1                   Dropout:            0.1
  Embed:              timeF               Activation:         gelu

Run Parameters
  Num Workers:        10                  Itr:                1
  Train Epochs:       10                  Batch Size:         32
  Patience:           3                   Learning Rate:      0.0001
  Des:                baseline            Loss:               MSE
  Lradj:              type1               Use Amp:            0

GPU
  Use GPU:            1                   GPU:                0
  Use Multi GPU:      0                   Devices:            0,1,2,3

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2

Use GPU: cuda:0
🚀 Lazy Loading: PatchTST ...
>>>>>>>start training : long_term_forecast_ETTh1_336_96_baseline_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh4_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8209
val 2785
test 2785
	iters: 100, epoch: 1 | loss: 0.4306515
	speed: 0.0404s/iter; left time: 99.7700s
	iters: 200, epoch: 1 | loss: 0.4137464
	speed: 0.0202s/iter; left time: 47.9673s
Epoch: 1 cost time: 5.99765682220459
Epoch: 1, Steps: 257 | Train Loss: 0.4214262 Vali Loss: 0.7315390 Test Loss: 0.3968201
Validation loss decreased (inf --> 0.731539).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.3947957
	speed: 0.0712s/iter; left time: 157.7063s
	iters: 200, epoch: 2 | loss: 0.3446186
	speed: 0.0202s/iter; left time: 42.7773s
Epoch: 2 cost time: 5.7525365352630615
Epoch: 2, Steps: 257 | Train Loss: 0.3796835 Vali Loss: 0.7161588 Test Loss: 0.3938735
Validation loss decreased (0.731539 --> 0.716159).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3837466
	speed: 0.0601s/iter; left time: 117.6925s
	iters: 200, epoch: 3 | loss: 0.3717185
	speed: 0.0227s/iter; left time: 42.0694s
Epoch: 3 cost time: 5.898083686828613
Epoch: 3, Steps: 257 | Train Loss: 0.3629771 Vali Loss: 0.6883598 Test Loss: 0.3777352
Validation loss decreased (0.716159 --> 0.688360).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3196180
	speed: 0.0612s/iter; left time: 103.9811s
	iters: 200, epoch: 4 | loss: 0.3352404
	speed: 0.0206s/iter; left time: 32.9694s
Epoch: 4 cost time: 5.681243658065796
Epoch: 4, Steps: 257 | Train Loss: 0.3559668 Vali Loss: 0.6817115 Test Loss: 0.3779413
Validation loss decreased (0.688360 --> 0.681711).  Saving model ...
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.2933395
	speed: 0.0669s/iter; left time: 96.5881s
	iters: 200, epoch: 5 | loss: 0.3018072
	speed: 0.0212s/iter; left time: 28.5090s
Epoch: 5 cost time: 6.000163316726685
Epoch: 5, Steps: 257 | Train Loss: 0.3517192 Vali Loss: 0.6810274 Test Loss: 0.3762230
Validation loss decreased (0.681711 --> 0.681027).  Saving model ...
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.3255947
	speed: 0.0615s/iter; left time: 72.9146s
	iters: 200, epoch: 6 | loss: 0.4565916
	speed: 0.0228s/iter; left time: 24.7810s
Epoch: 6 cost time: 5.986846923828125
Epoch: 6, Steps: 257 | Train Loss: 0.3502240 Vali Loss: 0.6774843 Test Loss: 0.3747531
Validation loss decreased (0.681027 --> 0.677484).  Saving model ...
Updating learning rate to 3.125e-06
	iters: 100, epoch: 7 | loss: 0.3713040
	speed: 0.0623s/iter; left time: 57.8349s
	iters: 200, epoch: 7 | loss: 0.3498178
	speed: 0.0211s/iter; left time: 17.4547s
Epoch: 7 cost time: 5.806391716003418
Epoch: 7, Steps: 257 | Train Loss: 0.3489504 Vali Loss: 0.6731616 Test Loss: 0.3747510
Validation loss decreased (0.677484 --> 0.673162).  Saving model ...
Updating learning rate to 1.5625e-06
	iters: 100, epoch: 8 | loss: 0.3473183
	speed: 0.0682s/iter; left time: 45.8081s
	iters: 200, epoch: 8 | loss: 0.3178993
	speed: 0.0249s/iter; left time: 14.2367s
Epoch: 8 cost time: 6.435657978057861
Epoch: 8, Steps: 257 | Train Loss: 0.3489114 Vali Loss: 0.6734234 Test Loss: 0.3746105
EarlyStopping counter: 1 out of 3
Updating learning rate to 7.8125e-07
	iters: 100, epoch: 9 | loss: 0.3054121
	speed: 0.0634s/iter; left time: 26.3014s
	iters: 200, epoch: 9 | loss: 0.3532648
	speed: 0.0232s/iter; left time: 7.2986s
Epoch: 9 cost time: 6.253446340560913
Epoch: 9, Steps: 257 | Train Loss: 0.3483759 Vali Loss: 0.6771917 Test Loss: 0.3744911
EarlyStopping counter: 2 out of 3
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.3325130
	speed: 0.0623s/iter; left time: 9.8391s
	iters: 200, epoch: 10 | loss: 0.3522374
	speed: 0.0216s/iter; left time: 1.2552s
Epoch: 10 cost time: 5.932294130325317
Epoch: 10, Steps: 257 | Train Loss: 0.3483089 Vali Loss: 0.6821511 Test Loss: 0.3745665
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : long_term_forecast_ETTh1_336_96_baseline_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh4_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
test shape: (2785, 96, 7) (2785, 96, 7)
test shape: (2785, 96, 7) (2785, 96, 7)
mse:0.37387576699256897, mae:0.3988799452781677, dtw:Not calculated

In [ ]:
!find /content/Time-Series-Library/checkpoints -type f

/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_336_96_baseline_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh4_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_0/checkpoint.pth

In [ ]:
import os
from google.colab import drive

# Ensure the mount point is clean before attempting to mount.
# This removes the /content/drive directory and all its contents.
if os.path.exists("/content/drive"):
    print("Clearing existing /content/drive mount point...")
    !rm -rf /content/drive
    print("/content/drive has been removed.")

drive.mount("/content/drive", force_remount=True)

Clearing existing /content/drive mount point...
/content/drive has been removed.
Mounted at /content/drive

In [ ]:
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

SCRIPT_DIR = PROJECT_DIR / "scripts"
RESULT_DIR = PROJECT_DIR / "results"
CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
CONFIG_DIR = PROJECT_DIR / "configs"

for directory in [
    SCRIPT_DIR,
    RESULT_DIR,
    CHECKPOINT_DIR,
    CONFIG_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

print("Proje klasörü:", PROJECT_DIR)

Proje klasörü: /content/drive/MyDrive/BIL401_Regime_Head_Pruning

In [ ]:
baseline_script = r"""#!/bin/bash

cd /content/Time-Series-Library

python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_336_96_baseline \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 4 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des baseline \
  --itr 1
"""

script_path = SCRIPT_DIR / "run_b0_patchtst_etth1.sh"
script_path.write_text(baseline_script, encoding="utf-8")

print("Komut kaydedildi:")
print(script_path)

Komut kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/scripts/run_b0_patchtst_etth1.sh

In [ ]:
from pathlib import Path

checkpoint_root = Path(
    "/content/Time-Series-Library/checkpoints"
)

baseline_checkpoints = [
    path
    for path in checkpoint_root.iterdir()
    if "ETTh1_336_96_baseline" in path.name
]

print("Bulunan checkpoint klasörleri:")

for path in baseline_checkpoints:
    print(path)

Bulunan checkpoint klasörleri:
/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_336_96_baseline_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh4_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_0

In [ ]:
import shutil

if len(baseline_checkpoints) != 1:
    raise RuntimeError(
        f"1 checkpoint bekleniyordu, "
        f"{len(baseline_checkpoints)} bulundu."
    )

source_checkpoint = baseline_checkpoints[0]

target_checkpoint = (
    CHECKPOINT_DIR
    / "B0_patchtst_etth1_336_dm128_h4"
)

if target_checkpoint.exists():
    shutil.rmtree(target_checkpoint)

shutil.copytree(
    source_checkpoint,
    target_checkpoint,
)

print("Checkpoint kaydedildi:")
print(target_checkpoint)

Checkpoint kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B0_patchtst_etth1_336_dm128_h4

In [ ]:
for path in target_checkpoint.rglob("*"):
    print(path)

/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B0_patchtst_etth1_336_dm128_h4/checkpoint.pth

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

RESULT_DIR = PROJECT_DIR / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

baseline_result = {
    "experiment_id": "B0_patchtst_etth1_336_dm128_h4",
    "model": "PatchTST",
    "dataset": "ETTh1",
    "seq_len": 336,
    "label_len": 48,
    "pred_len": 96,
    "d_model": 128,
    "d_ff": 256,
    "n_heads": 4,
    "e_layers": 3,
    "batch_size": 32,
    "max_epochs": 10,
    "best_epoch": 7,
    "patience": 3,
    "learning_rate": 0.0001,
    "best_val_loss": 0.6731616,
    "test_mse": 0.37387582659721375,
    "test_mae": 0.39887988567352295,
    "status": "completed",
}

results_path = RESULT_DIR / "baseline_experiments.csv"

if results_path.exists():
    results_df = pd.read_csv(results_path)
else:
    results_df = pd.DataFrame()

results_df = pd.concat(
    [
        results_df,
        pd.DataFrame([baseline_result]),
    ],
    ignore_index=True,
)

results_df = results_df.drop_duplicates(
    subset=["experiment_id"],
    keep="last",
)

results_df.to_csv(
    results_path,
    index=False,
)

display(results_df)

print("Sonuçlar kaydedildi:")
print(results_path)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed
2,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed

Sonuçlar kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/results/baseline_experiments.csv

In [ ]:
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

CONFIG_DIR = PROJECT_DIR / "configs"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

baseline_config = """
experiment_id: B0_patchtst_etth1_336_dm128_h4

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 4
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 336
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 10
  best_epoch: 7
  patience: 3
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.6731616
  test_mse: 0.37387582659721375
  test_mae: 0.39887988567352295

notes:
  description: baseline
  checkpoint_selected_by: validation_loss
""".strip()

config_path = (
    CONFIG_DIR
    / "B0_patchtst_etth1_336_dm128_h4.yaml"
)

config_path.write_text(
    baseline_config,
    encoding="utf-8",
)

print("Config kaydedildi:")
print(config_path)

Config kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/configs/B0_patchtst_etth1_336_dm128_h4.yaml

In [ ]:
print("CSV içeriği:")
display(pd.read_csv(results_path))

print("\nConfig içeriği:")
print(config_path.read_text(encoding="utf-8"))

CSV içeriği:

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status
0,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed
1,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed

Config içeriği:
experiment_id: B0_patchtst_etth1_336_dm128_h4

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 4
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 336
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 10
  best_epoch: 7
  patience: 3
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.6731616
  test_mse: 0.37387582659721375
  test_mae: 0.39887988567352295

notes:
  description: baseline
  checkpoint_selected_by: validation_loss

In [ ]:
%cd /content/Time-Series-Library

!python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_512_96_dm128_h16 \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --batch_size 32 \
  --train_epochs 20 \
  --patience 5 \
  --learning_rate 0.0001 \
  --des baseline_b1 \
  --itr 1

/content/Time-Series-Library
Using GPU
Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1
  Model ID:           ETTh1_512_96_dm128_h16Model:              PatchTST

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETDataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M
  Target:             OT                  Freq:               h
  Checkpoints:        ./checkpoints/

Forecasting Task
  Seq Len:            512                 Label Len:          48
  Pred Len:           96                  Seasonal Patterns:  Monthly
  Inverse:            0

Model Parameters
  Top k:              5                   Num Kernels:        6
  Enc In:             7                   Dec In:             7
  C Out:              7                   d model:            128
  n heads:            16                  e layers:           3
  d layers:           1                   d FF:               256
  Moving Avg:         25                  Factor:             3
  Distil:             1                   Dropout:            0.1
  Embed:              timeF               Activation:         gelu

Run Parameters
  Num Workers:        10                  Itr:                1
  Train Epochs:       20                  Batch Size:         32
  Patience:           5                   Learning Rate:      0.0001
  Des:                baseline_b1         Loss:               MSE
  Lradj:              type1               Use Amp:            0

GPU
  Use GPU:            1                   GPU:                0
  Use Multi GPU:      0                   Devices:            0,1,2,3

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2

Use GPU: cuda:0
🚀 Lazy Loading: PatchTST ...
>>>>>>>start training : long_term_forecast_ETTh1_512_96_dm128_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b1_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8033
val 2785
test 2785
	iters: 100, epoch: 1 | loss: 0.4667231
	speed: 0.0633s/iter; left time: 312.9842s
	iters: 200, epoch: 1 | loss: 0.3509181
	speed: 0.0436s/iter; left time: 211.0671s
Epoch: 1 cost time: 11.799287557601929
Epoch: 1, Steps: 252 | Train Loss: 0.4300319 Vali Loss: 0.7573440 Test Loss: 0.3987958
Validation loss decreased (inf --> 0.757344).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.4080897
	speed: 0.1072s/iter; left time: 502.6509s
	iters: 200, epoch: 2 | loss: 0.3910504
	speed: 0.0443s/iter; left time: 203.0647s
Epoch: 2 cost time: 11.535570621490479
Epoch: 2, Steps: 252 | Train Loss: 0.3838082 Vali Loss: 0.7389787 Test Loss: 0.3936104
Validation loss decreased (0.757344 --> 0.738979).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3568471
	speed: 0.1101s/iter; left time: 488.3200s
	iters: 200, epoch: 3 | loss: 0.3587312
	speed: 0.0450s/iter; left time: 195.1067s
Epoch: 3 cost time: 11.851016283035278
Epoch: 3, Steps: 252 | Train Loss: 0.3603303 Vali Loss: 0.7859216 Test Loss: 0.3860128
EarlyStopping counter: 1 out of 5
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3586521
	speed: 0.1164s/iter; left time: 487.1925s
	iters: 200, epoch: 4 | loss: 0.3285234
	speed: 0.0458s/iter; left time: 187.0939s
Epoch: 4 cost time: 12.19716191291809
Epoch: 4, Steps: 252 | Train Loss: 0.3502572 Vali Loss: 0.7587913 Test Loss: 0.3789293
EarlyStopping counter: 2 out of 5
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.3349445
	speed: 0.1176s/iter; left time: 462.5337s
	iters: 200, epoch: 5 | loss: 0.3635092
	speed: 0.0466s/iter; left time: 178.5570s
Epoch: 5 cost time: 12.127633810043335
Epoch: 5, Steps: 252 | Train Loss: 0.3445756 Vali Loss: 0.7595258 Test Loss: 0.3774536
EarlyStopping counter: 3 out of 5
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.3481042
	speed: 0.1162s/iter; left time: 427.7685s
	iters: 200, epoch: 6 | loss: 0.3090178
	speed: 0.0479s/iter; left time: 171.3620s
Epoch: 6 cost time: 12.387292385101318
Epoch: 6, Steps: 252 | Train Loss: 0.3419508 Vali Loss: 0.7382329 Test Loss: 0.3776003
Validation loss decreased (0.738979 --> 0.738233).  Saving model ...
Updating learning rate to 3.125e-06
	iters: 100, epoch: 7 | loss: 0.2999752
	speed: 0.1139s/iter; left time: 390.4272s
	iters: 200, epoch: 7 | loss: 0.3372696
	speed: 0.0472s/iter; left time: 157.0435s
Epoch: 7 cost time: 12.20835828781128
Epoch: 7, Steps: 252 | Train Loss: 0.3405674 Vali Loss: 0.7459204 Test Loss: 0.3771809
EarlyStopping counter: 1 out of 5
Updating learning rate to 1.5625e-06
	iters: 100, epoch: 8 | loss: 0.3620041
	speed: 0.1109s/iter; left time: 352.4056s
	iters: 200, epoch: 8 | loss: 0.4101428
	speed: 0.0463s/iter; left time: 142.4132s
Epoch: 8 cost time: 11.975260257720947
Epoch: 8, Steps: 252 | Train Loss: 0.3406739 Vali Loss: 0.7388639 Test Loss: 0.3771536
EarlyStopping counter: 2 out of 5
Updating learning rate to 7.8125e-07
	iters: 100, epoch: 9 | loss: 0.3320622
	speed: 0.1105s/iter; left time: 323.1008s
	iters: 200, epoch: 9 | loss: 0.3163607
	speed: 0.0461s/iter; left time: 130.3156s
Epoch: 9 cost time: 11.972157001495361
Epoch: 9, Steps: 252 | Train Loss: 0.3397966 Vali Loss: 0.7408104 Test Loss: 0.3770555
EarlyStopping counter: 3 out of 5
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.3181913
	speed: 0.1108s/iter; left time: 296.0701s
	iters: 200, epoch: 10 | loss: 0.3181522
	speed: 0.0466s/iter; left time: 119.9464s
Epoch: 10 cost time: 12.062278985977173
Epoch: 10, Steps: 252 | Train Loss: 0.3396195 Vali Loss: 0.7447575 Test Loss: 0.3771019
EarlyStopping counter: 4 out of 5
Updating learning rate to 1.953125e-07
	iters: 100, epoch: 11 | loss: 0.3977166
	speed: 0.1157s/iter; left time: 280.0719s
	iters: 200, epoch: 11 | loss: 0.3315838
	speed: 0.0471s/iter; left time: 109.3953s
Epoch: 11 cost time: 12.390696287155151
Epoch: 11, Steps: 252 | Train Loss: 0.3395864 Vali Loss: 0.7395977 Test Loss: 0.3773011
EarlyStopping counter: 5 out of 5
Early stopping
>>>>>>>testing : long_term_forecast_ETTh1_512_96_dm128_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b1_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
test shape: (2785, 96, 7) (2785, 96, 7)
test shape: (2785, 96, 7) (2785, 96, 7)
mse:0.37642404437065125, mae:0.40531599521636963, dtw:Not calculated

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

RESULT_DIR = PROJECT_DIR / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

results_path = RESULT_DIR / "baseline_experiments.csv"

b1_result = {
    "experiment_id": "B1_patchtst_etth1_512_dm128_h16",
    "model": "PatchTST",
    "dataset": "ETTh1",
    "seq_len": 512,
    "label_len": 48,
    "pred_len": 96,
    "d_model": 128,
    "d_ff": 256,
    "n_heads": 16,
    "e_layers": 3,
    "batch_size": 32,
    "max_epochs": 20,
    "best_epoch": 6,
    "patience": 5,
    "learning_rate": 0.0001,
    "best_val_loss": 0.7382330,
    "test_mse": 0.37642401456832886,
    "test_mae": 0.40531596541404724,
    "status": "completed",
}

if results_path.exists():
    results_df = pd.read_csv(results_path)
else:
    results_df = pd.DataFrame()

results_df = pd.concat(
    [results_df, pd.DataFrame([b1_result])],
    ignore_index=True,
)

results_df = results_df.drop_duplicates(
    subset=["experiment_id"],
    keep="last",
)

results_df.to_csv(results_path, index=False)

display(results_df)
print("Kaydedildi:", results_path)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status
1,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed
2,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed

Kaydedildi: /content/drive/MyDrive/BIL401_Regime_Head_Pruning/results/baseline_experiments.csv

In [ ]:
CONFIG_DIR = PROJECT_DIR / "configs"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

b1_config = """
experiment_id: B1_patchtst_etth1_512_dm128_h16

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 16
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 512
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 20
  best_epoch: 6
  patience: 5
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.7382330
  test_mse: 0.37642401456832886
  test_mae: 0.40531596541404724

notes:
  description: baseline_b1
  checkpoint_selected_by: validation_loss
""".strip()

config_path = (
    CONFIG_DIR
    / "B1_patchtst_etth1_512_dm128_h16.yaml"
)

config_path.write_text(
    b1_config,
    encoding="utf-8",
)

print("Config kaydedildi:")
print(config_path)

Config kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/configs/B1_patchtst_etth1_512_dm128_h16.yaml

In [ ]:
from pathlib import Path

checkpoint_root = Path(
    "/content/Time-Series-Library/checkpoints"
)

b1_matches = [
    path
    for path in checkpoint_root.iterdir()
    if "ETTh1_512_96_dm128_h16" in path.name
]

print("Bulunan B1 checkpoint klasörleri:")

for path in b1_matches:
    print(path)

Bulunan B1 checkpoint klasörleri:
/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_512_96_dm128_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b1_0

In [ ]:
import shutil

CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

if len(b1_matches) != 1:
    raise RuntimeError(
        f"1 B1 checkpoint bekleniyordu, {len(b1_matches)} bulundu."
    )

source_b1 = b1_matches[0]

target_b1 = (
    CHECKPOINT_DIR
    / "B1_patchtst_etth1_512_dm128_h16"
)

if target_b1.exists():
    shutil.rmtree(target_b1)

shutil.copytree(
    source_b1,
    target_b1,
)

print("B1 checkpoint kaydedildi:")
print(target_b1)

print("CSV:")
display(pd.read_csv(results_path))

print("\nConfig:")
print(config_path.read_text(encoding="utf-8"))

print("\nCheckpoint dosyaları:")
for path in target_b1.rglob("*"):
    print(path)

B1 checkpoint kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B1_patchtst_etth1_512_dm128_h16
CSV:

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed

Config:
experiment_id: B1_patchtst_etth1_512_dm128_h16

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 16
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 512
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 20
  best_epoch: 6
  patience: 5
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.7382330
  test_mse: 0.37642401456832886
  test_mae: 0.40531596541404724

notes:
  description: baseline_b1
  checkpoint_selected_by: validation_loss

Checkpoint dosyaları:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B1_patchtst_etth1_512_dm128_h16/checkpoint.pth

In [ ]:
%cd /content/Time-Series-Library

!python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_512_96_dm256_h16 \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 512 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 256 \
  --d_ff 512 \
  --n_heads 16 \
  --batch_size 32 \
  --train_epochs 20 \
  --patience 5 \
  --learning_rate 0.0001 \
  --des baseline_b2 \
  --itr 1

/content/Time-Series-Library
Using GPU
Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1
  Model ID:           ETTh1_512_96_dm256_h16Model:              PatchTST

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETDataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M
  Target:             OT                  Freq:               h
  Checkpoints:        ./checkpoints/

Forecasting Task
  Seq Len:            512                 Label Len:          48
  Pred Len:           96                  Seasonal Patterns:  Monthly
  Inverse:            0

Model Parameters
  Top k:              5                   Num Kernels:        6
  Enc In:             7                   Dec In:             7
  C Out:              7                   d model:            256
  n heads:            16                  e layers:           3
  d layers:           1                   d FF:               512
  Moving Avg:         25                  Factor:             3
  Distil:             1                   Dropout:            0.1
  Embed:              timeF               Activation:         gelu

Run Parameters
  Num Workers:        10                  Itr:                1
  Train Epochs:       20                  Batch Size:         32
  Patience:           5                   Learning Rate:      0.0001
  Des:                baseline_b2         Loss:               MSE
  Lradj:              type1               Use Amp:            0

GPU
  Use GPU:            1                   GPU:                0
  Use Multi GPU:      0                   Devices:            0,1,2,3

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2

Use GPU: cuda:0
🚀 Lazy Loading: PatchTST ...
>>>>>>>start training : long_term_forecast_ETTh1_512_96_dm256_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm256_nh16_el3_dl1_df512_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b2_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8033
val 2785
test 2785
	iters: 100, epoch: 1 | loss: 0.3785275
	speed: 0.1150s/iter; left time: 568.0026s
	iters: 200, epoch: 1 | loss: 0.3352827
	speed: 0.0909s/iter; left time: 439.9591s
Epoch: 1 cost time: 23.808409929275513
Epoch: 1, Steps: 252 | Train Loss: 0.4296095 Vali Loss: 0.8658466 Test Loss: 0.4107741
Validation loss decreased (inf --> 0.865847).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.3463824
	speed: 0.2099s/iter; left time: 984.2794s
	iters: 200, epoch: 2 | loss: 0.3588050
	speed: 0.0906s/iter; left time: 415.6213s
Epoch: 2 cost time: 23.242900133132935
Epoch: 2, Steps: 252 | Train Loss: 0.3782864 Vali Loss: 0.8354515 Test Loss: 0.4242905
Validation loss decreased (0.865847 --> 0.835451).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3899933
	speed: 0.2049s/iter; left time: 909.0661s
	iters: 200, epoch: 3 | loss: 0.3101950
	speed: 0.0890s/iter; left time: 385.7826s
Epoch: 3 cost time: 23.034952640533447
Epoch: 3, Steps: 252 | Train Loss: 0.3459773 Vali Loss: 0.7827365 Test Loss: 0.3937002
Validation loss decreased (0.835451 --> 0.782736).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3171377
	speed: 0.2059s/iter; left time: 861.8512s
	iters: 200, epoch: 4 | loss: 0.3307526
	speed: 0.0917s/iter; left time: 374.7519s
Epoch: 4 cost time: 23.428566932678223
Epoch: 4, Steps: 252 | Train Loss: 0.3295933 Vali Loss: 0.7859426 Test Loss: 0.3972968
EarlyStopping counter: 1 out of 5
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.3761413
	speed: 0.2058s/iter; left time: 809.5962s
	iters: 200, epoch: 5 | loss: 0.2991844
	speed: 0.0899s/iter; left time: 344.5489s
Epoch: 5 cost time: 23.094756364822388
Epoch: 5, Steps: 252 | Train Loss: 0.3232761 Vali Loss: 0.7811291 Test Loss: 0.3956731
Validation loss decreased (0.782736 --> 0.781129).  Saving model ...
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.3035583
	speed: 0.2030s/iter; left time: 747.0604s
	iters: 200, epoch: 6 | loss: 0.3373869
	speed: 0.0895s/iter; left time: 320.4480s
Epoch: 6 cost time: 22.980766534805298
Epoch: 6, Steps: 252 | Train Loss: 0.3179185 Vali Loss: 0.7846245 Test Loss: 0.3945687
EarlyStopping counter: 1 out of 5
Updating learning rate to 3.125e-06
	iters: 100, epoch: 7 | loss: 0.3436530
	speed: 0.2016s/iter; left time: 691.2773s
	iters: 200, epoch: 7 | loss: 0.3562682
	speed: 0.0907s/iter; left time: 301.9569s
Epoch: 7 cost time: 23.1524555683136
Epoch: 7, Steps: 252 | Train Loss: 0.3157276 Vali Loss: 0.7813542 Test Loss: 0.3993161
EarlyStopping counter: 2 out of 5
Updating learning rate to 1.5625e-06
	iters: 100, epoch: 8 | loss: 0.3161365
	speed: 0.2018s/iter; left time: 641.0677s
	iters: 200, epoch: 8 | loss: 0.3757542
	speed: 0.0897s/iter; left time: 276.0357s
Epoch: 8 cost time: 22.964323043823242
Epoch: 8, Steps: 252 | Train Loss: 0.3151220 Vali Loss: 0.7930388 Test Loss: 0.3986729
EarlyStopping counter: 3 out of 5
Updating learning rate to 7.8125e-07
	iters: 100, epoch: 9 | loss: 0.3187765
	speed: 0.2006s/iter; left time: 586.7714s
	iters: 200, epoch: 9 | loss: 0.3652543
	speed: 0.0899s/iter; left time: 254.0324s
Epoch: 9 cost time: 23.02130436897278
Epoch: 9, Steps: 252 | Train Loss: 0.3139420 Vali Loss: 0.7816318 Test Loss: 0.4003181
EarlyStopping counter: 4 out of 5
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.2989124
	speed: 0.2020s/iter; left time: 539.9298s
	iters: 200, epoch: 10 | loss: 0.3176336
	speed: 0.0908s/iter; left time: 233.5799s
Epoch: 10 cost time: 23.123845100402832
Epoch: 10, Steps: 252 | Train Loss: 0.3142604 Vali Loss: 0.7869027 Test Loss: 0.3978760
EarlyStopping counter: 5 out of 5
Early stopping
>>>>>>>testing : long_term_forecast_ETTh1_512_96_dm256_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm256_nh16_el3_dl1_df512_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b2_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
test shape: (2785, 96, 7) (2785, 96, 7)
test shape: (2785, 96, 7) (2785, 96, 7)
mse:0.39473891258239746, mae:0.4233819246292114, dtw:Not calculated

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

RESULT_DIR = PROJECT_DIR / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

results_path = RESULT_DIR / "baseline_experiments.csv"

b2_result = {
    "experiment_id": "B2_patchtst_etth1_512_dm256_h16",
    "model": "PatchTST",
    "dataset": "ETTh1",
    "seq_len": 512,
    "label_len": 48,
    "pred_len": 96,
    "d_model": 256,
    "d_ff": 512,
    "n_heads": 16,
    "e_layers": 3,
    "batch_size": 32,
    "max_epochs": 20,
    "best_epoch": 5,
    "patience": 5,
    "learning_rate": 0.0001,
    "best_val_loss": 0.7811291,
    "test_mse": 0.39473891258239746,
    "test_mae": 0.4233819246292114,
    "status": "completed",
    "rerun_confirmed": True,
}

if results_path.exists():
    results_df = pd.read_csv(results_path)
else:
    results_df = pd.DataFrame()

results_df = pd.concat(
    [results_df, pd.DataFrame([b2_result])],
    ignore_index=True,
)

results_df = results_df.drop_duplicates(
    subset=["experiment_id"],
    keep="last",
)

results_df.to_csv(results_path, index=False)

display(results_df)
print("B2 sonucu kaydedildi:")
print(results_path)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status,rerun_confirmed
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed,NaN
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed,NaN
2,B2_patchtst_etth1_512_dm256_h16,PatchTST,ETTh1,512,48,96,256,512,16,3,32,20,5,5,0.0001,0.781129,0.394739,0.423382,completed,True

B2 sonucu kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/results/baseline_experiments.csv

In [ ]:
CONFIG_DIR = PROJECT_DIR / "configs"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

b2_config = """
experiment_id: B2_patchtst_etth1_512_dm256_h16

model:
  name: PatchTST
  d_model: 256
  d_ff: 512
  n_heads: 16
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 512
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 20
  best_epoch: 5
  patience: 5
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.7811291
  test_mse: 0.39473891258239746
  test_mae: 0.4233819246292114

reproducibility:
  rerun_completed: true
  rerun_result_identical: true

notes:
  description: baseline_b2
  checkpoint_selected_by: validation_loss
""".strip()

b2_config_path = (
    CONFIG_DIR
    / "B2_patchtst_etth1_512_dm256_h16.yaml"
)

b2_config_path.write_text(
    b2_config,
    encoding="utf-8",
)

print("B2 config kaydedildi:")
print(b2_config_path)

B2 config kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/configs/B2_patchtst_etth1_512_dm256_h16.yaml

In [ ]:
from pathlib import Path

checkpoint_root = Path(
    "/content/Time-Series-Library/checkpoints"
)

b2_matches = [
    path
    for path in checkpoint_root.iterdir()
    if "ETTh1_512_96_dm256_h16" in path.name
]

print("Bulunan B2 checkpoint klasörleri:")

for path in b2_matches:
    print(path)

Bulunan B2 checkpoint klasörleri:
/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_512_96_dm256_h16_PatchTST_ETTh1_ftM_sl512_ll48_pl96_dm256_nh16_el3_dl1_df512_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b2_0

In [ ]:
import shutil

CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

if len(b2_matches) != 1:
    raise RuntimeError(
        f"1 B2 checkpoint bekleniyordu, {len(b2_matches)} bulundu."
    )

source_b2 = b2_matches[0]

target_b2 = (
    CHECKPOINT_DIR
    / "B2_patchtst_etth1_512_dm256_h16"
)

if target_b2.exists():
    shutil.rmtree(target_b2)

shutil.copytree(
    source_b2,
    target_b2,
)

print("B2 checkpoint yeniden kaydedildi:")
print(target_b2)

B2 checkpoint yeniden kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B2_patchtst_etth1_512_dm256_h16

In [ ]:
print("CSV:")
display(pd.read_csv(results_path))

print("\nConfig:")
print(b2_config_path.read_text(encoding="utf-8"))

print("\nCheckpoint dosyaları:")
for path in target_b2.rglob("*"):
    print(path)

CSV:

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status,rerun_confirmed
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed,NaN
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed,NaN
2,B2_patchtst_etth1_512_dm256_h16,PatchTST,ETTh1,512,48,96,256,512,16,3,32,20,5,5,0.0001,0.781129,0.394739,0.423382,completed,True

Config:
experiment_id: B2_patchtst_etth1_512_dm256_h16

model:
  name: PatchTST
  d_model: 256
  d_ff: 512
  n_heads: 16
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 512
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 20
  best_epoch: 5
  patience: 5
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.7811291
  test_mse: 0.39473891258239746
  test_mae: 0.4233819246292114

reproducibility:
  rerun_completed: true
  rerun_result_identical: true

notes:
  description: baseline_b2
  checkpoint_selected_by: validation_loss

Checkpoint dosyaları:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B2_patchtst_etth1_512_dm256_h16/checkpoint.pth

In [ ]:
results_df = pd.read_csv(results_path)

comparison_columns = [
    "experiment_id",
    "seq_len",
    "d_model",
    "d_ff",
    "n_heads",
    "best_epoch",
    "best_val_loss",
    "test_mse",
    "test_mae",
]

comparison_df = (
    results_df[comparison_columns]
    .sort_values("best_val_loss")
    .reset_index(drop=True)
)

display(comparison_df)

,experiment_id,seq_len,d_model,d_ff,n_heads,best_epoch,best_val_loss,test_mse,test_mae
0,B0_patchtst_etth1_336_dm128_h4,336,128,256,4,7,0.673162,0.373876,0.398880
1,B1_patchtst_etth1_512_dm128_h16,512,128,256,16,6,0.738233,0.376424,0.405316
2,B2_patchtst_etth1_512_dm256_h16,512,256,512,16,5,0.781129,0.394739,0.423382

In [ ]:
%cd /content/Time-Series-Library

!python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_336_96_dm128_h16 \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 16 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des baseline_b3 \
  --itr 1

/content/Time-Series-Library
Using GPU
Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1
  Model ID:           ETTh1_336_96_dm128_h16Model:              PatchTST

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETDataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M
  Target:             OT                  Freq:               h
  Checkpoints:        ./checkpoints/

Forecasting Task
  Seq Len:            336                 Label Len:          48
  Pred Len:           96                  Seasonal Patterns:  Monthly
  Inverse:            0

Model Parameters
  Top k:              5                   Num Kernels:        6
  Enc In:             7                   Dec In:             7
  C Out:              7                   d model:            128
  n heads:            16                  e layers:           3
  d layers:           1                   d FF:               256
  Moving Avg:         25                  Factor:             3
  Distil:             1                   Dropout:            0.1
  Embed:              timeF               Activation:         gelu

Run Parameters
  Num Workers:        10                  Itr:                1
  Train Epochs:       10                  Batch Size:         32
  Patience:           3                   Learning Rate:      0.0001
  Des:                baseline_b3         Loss:               MSE
  Lradj:              type1               Use Amp:            0

GPU
  Use GPU:            1                   GPU:                0
  Use Multi GPU:      0                   Devices:            0,1,2,3

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2

Use GPU: cuda:0
🚀 Lazy Loading: PatchTST ...
>>>>>>>start training : long_term_forecast_ETTh1_336_96_dm128_h16_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b3_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8209
val 2785
test 2785
	iters: 100, epoch: 1 | loss: 0.4276939
	speed: 0.0486s/iter; left time: 120.1343s
	iters: 200, epoch: 1 | loss: 0.4185023
	speed: 0.0305s/iter; left time: 72.3464s
Epoch: 1 cost time: 8.589237451553345
Epoch: 1, Steps: 257 | Train Loss: 0.4220656 Vali Loss: 0.7299377 Test Loss: 0.3967650
Validation loss decreased (inf --> 0.729938).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.3907284
	speed: 0.0803s/iter; left time: 177.8842s
	iters: 200, epoch: 2 | loss: 0.3480385
	speed: 0.0306s/iter; left time: 64.7789s
Epoch: 2 cost time: 8.327287673950195
Epoch: 2, Steps: 257 | Train Loss: 0.3810270 Vali Loss: 0.7184746 Test Loss: 0.3925545
Validation loss decreased (0.729938 --> 0.718475).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3873662
	speed: 0.0886s/iter; left time: 173.4240s
	iters: 200, epoch: 3 | loss: 0.3709744
	speed: 0.0314s/iter; left time: 58.3947s
Epoch: 3 cost time: 8.864731311798096
Epoch: 3, Steps: 257 | Train Loss: 0.3639234 Vali Loss: 0.6930032 Test Loss: 0.3786596
Validation loss decreased (0.718475 --> 0.693003).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3147117
	speed: 0.0906s/iter; left time: 154.0297s
	iters: 200, epoch: 4 | loss: 0.3323154
	speed: 0.0310s/iter; left time: 49.6349s
Epoch: 4 cost time: 8.409425020217896
Epoch: 4, Steps: 257 | Train Loss: 0.3565894 Vali Loss: 0.6831741 Test Loss: 0.3768752
Validation loss decreased (0.693003 --> 0.683174).  Saving model ...
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.2950712
	speed: 0.0898s/iter; left time: 129.5536s
	iters: 200, epoch: 5 | loss: 0.2984290
	speed: 0.0304s/iter; left time: 40.7966s
Epoch: 5 cost time: 8.411870002746582
Epoch: 5, Steps: 257 | Train Loss: 0.3522292 Vali Loss: 0.6838592 Test Loss: 0.3757403
EarlyStopping counter: 1 out of 3
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.3252157
	speed: 0.0822s/iter; left time: 97.5439s
	iters: 200, epoch: 6 | loss: 0.4564814
	speed: 0.0305s/iter; left time: 33.0753s
Epoch: 6 cost time: 8.30607557296753
Epoch: 6, Steps: 257 | Train Loss: 0.3504660 Vali Loss: 0.6830628 Test Loss: 0.3750410
Validation loss decreased (0.683174 --> 0.683063).  Saving model ...
Updating learning rate to 3.125e-06
	iters: 100, epoch: 7 | loss: 0.3727167
	speed: 0.0801s/iter; left time: 74.4412s
	iters: 200, epoch: 7 | loss: 0.3530122
	speed: 0.0311s/iter; left time: 25.8202s
Epoch: 7 cost time: 8.246253252029419
Epoch: 7, Steps: 257 | Train Loss: 0.3492684 Vali Loss: 0.6781806 Test Loss: 0.3745288
Validation loss decreased (0.683063 --> 0.678181).  Saving model ...
Updating learning rate to 1.5625e-06
	iters: 100, epoch: 8 | loss: 0.3417110
	speed: 0.0815s/iter; left time: 54.7398s
	iters: 200, epoch: 8 | loss: 0.3162542
	speed: 0.0304s/iter; left time: 17.3824s
Epoch: 8 cost time: 8.30410647392273
Epoch: 8, Steps: 257 | Train Loss: 0.3488082 Vali Loss: 0.6780880 Test Loss: 0.3743904
Validation loss decreased (0.678181 --> 0.678088).  Saving model ...
Updating learning rate to 7.8125e-07
	iters: 100, epoch: 9 | loss: 0.3032313
	speed: 0.0869s/iter; left time: 36.0639s
	iters: 200, epoch: 9 | loss: 0.3666785
	speed: 0.0304s/iter; left time: 9.5718s
Epoch: 9 cost time: 8.203120708465576
Epoch: 9, Steps: 257 | Train Loss: 0.3482319 Vali Loss: 0.6816983 Test Loss: 0.3743587
EarlyStopping counter: 1 out of 3
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.3368394
	speed: 0.0889s/iter; left time: 14.0385s
	iters: 200, epoch: 10 | loss: 0.3555582
	speed: 0.0308s/iter; left time: 1.7841s
Epoch: 10 cost time: 8.57160997390747
Epoch: 10, Steps: 257 | Train Loss: 0.3488119 Vali Loss: 0.6874044 Test Loss: 0.3744267
EarlyStopping counter: 2 out of 3
Updating learning rate to 1.953125e-07
>>>>>>>testing : long_term_forecast_ETTh1_336_96_dm128_h16_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b3_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
test shape: (2785, 96, 7) (2785, 96, 7)
test shape: (2785, 96, 7) (2785, 96, 7)
mse:0.3735102415084839, mae:0.39940717816352844, dtw:Not calculated

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

RESULT_DIR = PROJECT_DIR / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

results_path = RESULT_DIR / "baseline_experiments.csv"

b3_result = {
    "experiment_id": "B3_patchtst_etth1_336_dm128_h16",
    "model": "PatchTST",
    "dataset": "ETTh1",
    "seq_len": 336,
    "label_len": 48,
    "pred_len": 96,
    "d_model": 128,
    "d_ff": 256,
    "n_heads": 16,
    "e_layers": 3,
    "batch_size": 32,
    "max_epochs": 10,
    "best_epoch": 8,
    "patience": 3,
    "learning_rate": 0.0001,
    "best_val_loss": 0.6780880,
    "test_mse": 0.3735102415084839,
    "test_mae": 0.39940717816352844,
    "status": "completed",
}

if results_path.exists():
    results_df = pd.read_csv(results_path)
else:
    results_df = pd.DataFrame()

results_df = pd.concat(
    [results_df, pd.DataFrame([b3_result])],
    ignore_index=True,
)

results_df = results_df.drop_duplicates(
    subset=["experiment_id"],
    keep="last",
)

results_df.to_csv(results_path, index=False)

display(results_df)
print("B3 sonucu kaydedildi:")
print(results_path)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status,rerun_confirmed
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed,NaN
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed,NaN
2,B2_patchtst_etth1_512_dm256_h16,PatchTST,ETTh1,512,48,96,256,512,16,3,32,20,5,5,0.0001,0.781129,0.394739,0.423382,completed,True
3,B3_patchtst_etth1_336_dm128_h16,PatchTST,ETTh1,336,48,96,128,256,16,3,32,10,8,3,0.0001,0.678088,0.373510,0.399407,completed,NaN

B3 sonucu kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/results/baseline_experiments.csv

In [ ]:
CONFIG_DIR = PROJECT_DIR / "configs"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

b3_config = """
experiment_id: B3_patchtst_etth1_336_dm128_h16

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 16
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 336
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 10
  best_epoch: 8
  patience: 3
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.6780880
  test_mse: 0.3735102415084839
  test_mae: 0.39940717816352844

notes:
  description: baseline_b3
  checkpoint_selected_by: validation_loss
""".strip()

b3_config_path = (
    CONFIG_DIR
    / "B3_patchtst_etth1_336_dm128_h16.yaml"
)

b3_config_path.write_text(
    b3_config,
    encoding="utf-8",
)

print("B3 config kaydedildi:")
print(b3_config_path)

B3 config kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/configs/B3_patchtst_etth1_336_dm128_h16.yaml

In [ ]:
from pathlib import Path

checkpoint_root = Path(
    "/content/Time-Series-Library/checkpoints"
)

b3_matches = [
    path
    for path in checkpoint_root.iterdir()
    if "ETTh1_336_96_dm128_h16" in path.name
]

for path in b3_matches:
    print(path)

/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_336_96_dm128_h16_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh16_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b3_0

In [ ]:
import shutil

CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

if len(b3_matches) != 1:
    raise RuntimeError(
        f"1 B3 checkpoint bekleniyordu, {len(b3_matches)} bulundu."
    )

source_b3 = b3_matches[0]

target_b3 = (
    CHECKPOINT_DIR
    / "B3_patchtst_etth1_336_dm128_h16"
)

if target_b3.exists():
    shutil.rmtree(target_b3)

shutil.copytree(
    source_b3,
    target_b3,
)

print("B3 checkpoint kaydedildi:")
print(target_b3)

B3 checkpoint kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B3_patchtst_etth1_336_dm128_h16

In [ ]:
%cd /content/Time-Series-Library

!python -u run.py \
  --task_name long_term_forecast \
  --is_training 1 \
  --root_path ./dataset/ETDataset/ETT-small/ \
  --data_path ETTh1.csv \
  --model_id ETTh1_336_96_dm128_h8 \
  --model PatchTST \
  --data ETTh1 \
  --features M \
  --seq_len 336 \
  --label_len 48 \
  --pred_len 96 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --d_model 128 \
  --d_ff 256 \
  --n_heads 8 \
  --batch_size 32 \
  --train_epochs 10 \
  --patience 3 \
  --learning_rate 0.0001 \
  --des baseline_b4 \
  --itr 1

/content/Time-Series-Library
Using GPU
Args in experiment:
Basic Config
  Task Name:          long_term_forecast  Is Training:        1
  Model ID:           ETTh1_336_96_dm128_h8Model:              PatchTST

Data Loader
  Data:               ETTh1               Root Path:          ./dataset/ETDataset/ETT-small/
  Data Path:          ETTh1.csv           Features:           M
  Target:             OT                  Freq:               h
  Checkpoints:        ./checkpoints/

Forecasting Task
  Seq Len:            336                 Label Len:          48
  Pred Len:           96                  Seasonal Patterns:  Monthly
  Inverse:            0

Model Parameters
  Top k:              5                   Num Kernels:        6
  Enc In:             7                   Dec In:             7
  C Out:              7                   d model:            128
  n heads:            8                   e layers:           3
  d layers:           1                   d FF:               256
  Moving Avg:         25                  Factor:             3
  Distil:             1                   Dropout:            0.1
  Embed:              timeF               Activation:         gelu

Run Parameters
  Num Workers:        10                  Itr:                1
  Train Epochs:       10                  Batch Size:         32
  Patience:           3                   Learning Rate:      0.0001
  Des:                baseline_b4         Loss:               MSE
  Lradj:              type1               Use Amp:            0

GPU
  Use GPU:            1                   GPU:                0
  Use Multi GPU:      0                   Devices:            0,1,2,3

De-stationary Projector Params
  P Hidden Dims:      128, 128            P Hidden Layers:    2

Use GPU: cuda:0
🚀 Lazy Loading: PatchTST ...
>>>>>>>start training : long_term_forecast_ETTh1_336_96_dm128_h8_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh8_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b4_0>>>>>>>>>>>>>>>>>>>>>>>>>>
train 8209
val 2785
test 2785
	iters: 100, epoch: 1 | loss: 0.4295151
	speed: 0.0427s/iter; left time: 105.4227s
	iters: 200, epoch: 1 | loss: 0.4154102
	speed: 0.0257s/iter; left time: 60.8988s
Epoch: 1 cost time: 7.3096654415130615
Epoch: 1, Steps: 257 | Train Loss: 0.4217984 Vali Loss: 0.7306948 Test Loss: 0.3969414
Validation loss decreased (inf --> 0.730695).  Saving model ...
Updating learning rate to 0.0001
	iters: 100, epoch: 2 | loss: 0.3963138
	speed: 0.0715s/iter; left time: 158.2080s
	iters: 200, epoch: 2 | loss: 0.3520744
	speed: 0.0251s/iter; left time: 53.0250s
Epoch: 2 cost time: 6.851214647293091
Epoch: 2, Steps: 257 | Train Loss: 0.3805242 Vali Loss: 0.7182832 Test Loss: 0.3928833
Validation loss decreased (0.730695 --> 0.718283).  Saving model ...
Updating learning rate to 5e-05
	iters: 100, epoch: 3 | loss: 0.3821889
	speed: 0.0820s/iter; left time: 160.5520s
	iters: 200, epoch: 3 | loss: 0.3708694
	speed: 0.0255s/iter; left time: 47.3492s
Epoch: 3 cost time: 7.4827964305877686
Epoch: 3, Steps: 257 | Train Loss: 0.3634309 Vali Loss: 0.6893346 Test Loss: 0.3774374
Validation loss decreased (0.718283 --> 0.689335).  Saving model ...
Updating learning rate to 2.5e-05
	iters: 100, epoch: 4 | loss: 0.3210790
	speed: 0.0734s/iter; left time: 124.7233s
	iters: 200, epoch: 4 | loss: 0.3340530
	speed: 0.0266s/iter; left time: 42.5584s
Epoch: 4 cost time: 7.167078733444214
Epoch: 4, Steps: 257 | Train Loss: 0.3559083 Vali Loss: 0.6806074 Test Loss: 0.3761475
Validation loss decreased (0.689335 --> 0.680607).  Saving model ...
Updating learning rate to 1.25e-05
	iters: 100, epoch: 5 | loss: 0.3045839
	speed: 0.0724s/iter; left time: 104.4220s
	iters: 200, epoch: 5 | loss: 0.2985112
	speed: 0.0254s/iter; left time: 34.1612s
Epoch: 5 cost time: 7.043498516082764
Epoch: 5, Steps: 257 | Train Loss: 0.3518852 Vali Loss: 0.6804417 Test Loss: 0.3747753
Validation loss decreased (0.680607 --> 0.680442).  Saving model ...
Updating learning rate to 6.25e-06
	iters: 100, epoch: 6 | loss: 0.3237852
	speed: 0.0779s/iter; left time: 92.3681s
	iters: 200, epoch: 6 | loss: 0.4562311
	speed: 0.0248s/iter; left time: 26.9390s
Epoch: 6 cost time: 6.8295512199401855
Epoch: 6, Steps: 257 | Train Loss: 0.3496000 Vali Loss: 0.6792158 Test Loss: 0.3738758
Validation loss decreased (0.680442 --> 0.679216).  Saving model ...
Updating learning rate to 3.125e-06
	iters: 100, epoch: 7 | loss: 0.3683666
	speed: 0.0729s/iter; left time: 67.7453s
	iters: 200, epoch: 7 | loss: 0.3494894
	speed: 0.0250s/iter; left time: 20.6956s
Epoch: 7 cost time: 7.001773834228516
Epoch: 7, Steps: 257 | Train Loss: 0.3486772 Vali Loss: 0.6734824 Test Loss: 0.3734598
Validation loss decreased (0.679216 --> 0.673482).  Saving model ...
Updating learning rate to 1.5625e-06
	iters: 100, epoch: 8 | loss: 0.3455576
	speed: 0.0691s/iter; left time: 46.4180s
	iters: 200, epoch: 8 | loss: 0.3186553
	speed: 0.0252s/iter; left time: 14.4246s
Epoch: 8 cost time: 6.895654201507568
Epoch: 8, Steps: 257 | Train Loss: 0.3485325 Vali Loss: 0.6738191 Test Loss: 0.3733659
EarlyStopping counter: 1 out of 3
Updating learning rate to 7.8125e-07
	iters: 100, epoch: 9 | loss: 0.3016818
	speed: 0.0734s/iter; left time: 30.4534s
	iters: 200, epoch: 9 | loss: 0.3622290
	speed: 0.0249s/iter; left time: 7.8357s
Epoch: 9 cost time: 6.806441783905029
Epoch: 9, Steps: 257 | Train Loss: 0.3479265 Vali Loss: 0.6778159 Test Loss: 0.3732253
EarlyStopping counter: 2 out of 3
Updating learning rate to 3.90625e-07
	iters: 100, epoch: 10 | loss: 0.3316293
	speed: 0.0758s/iter; left time: 11.9835s
	iters: 200, epoch: 10 | loss: 0.3526897
	speed: 0.0250s/iter; left time: 1.4499s
Epoch: 10 cost time: 7.054941654205322
Epoch: 10, Steps: 257 | Train Loss: 0.3481519 Vali Loss: 0.6827647 Test Loss: 0.3733862
EarlyStopping counter: 3 out of 3
Early stopping
>>>>>>>testing : long_term_forecast_ETTh1_336_96_dm128_h8_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh8_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b4_0<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
test 2785
test shape: (2785, 96, 7) (2785, 96, 7)
test shape: (2785, 96, 7) (2785, 96, 7)
mse:0.37254568934440613, mae:0.3982141613960266, dtw:Not calculated

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

RESULT_DIR = PROJECT_DIR / "results"
RESULT_DIR.mkdir(parents=True, exist_ok=True)

results_path = RESULT_DIR / "baseline_experiments.csv"

b4_result = {
    "experiment_id": "B4_patchtst_etth1_336_dm128_h8",
    "model": "PatchTST",
    "dataset": "ETTh1",
    "seq_len": 336,
    "label_len": 48,
    "pred_len": 96,
    "d_model": 128,
    "d_ff": 256,
    "n_heads": 8,
    "e_layers": 3,
    "batch_size": 32,
    "max_epochs": 10,
    "best_epoch": 7,
    "patience": 3,
    "learning_rate": 0.0001,
    "best_val_loss": 0.6734824,
    "test_mse": 0.37254568934440613,
    "test_mae": 0.3982141613960266,
    "status": "completed",
}

if results_path.exists():
    results_df = pd.read_csv(results_path)
else:
    results_df = pd.DataFrame()

results_df = pd.concat(
    [results_df, pd.DataFrame([b4_result])],
    ignore_index=True,
)

results_df = results_df.drop_duplicates(
    subset=["experiment_id"],
    keep="last",
)

results_df.to_csv(results_path, index=False)

display(results_df)
print("B4 sonucu kaydedildi:")
print(results_path)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,batch_size,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status,rerun_confirmed
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,32,10,7,3,0.0001,0.673162,0.373876,0.398880,completed,NaN
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,32,20,6,5,0.0001,0.738233,0.376424,0.405316,completed,NaN
2,B2_patchtst_etth1_512_dm256_h16,PatchTST,ETTh1,512,48,96,256,512,16,3,32,20,5,5,0.0001,0.781129,0.394739,0.423382,completed,True
3,B3_patchtst_etth1_336_dm128_h16,PatchTST,ETTh1,336,48,96,128,256,16,3,32,10,8,3,0.0001,0.678088,0.373510,0.399407,completed,NaN
4,B4_patchtst_etth1_336_dm128_h8,PatchTST,ETTh1,336,48,96,128,256,8,3,32,10,7,3,0.0001,0.673482,0.372546,0.398214,completed,NaN

B4 sonucu kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/results/baseline_experiments.csv

In [ ]:
CONFIG_DIR = PROJECT_DIR / "configs"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

b4_config = """
experiment_id: B4_patchtst_etth1_336_dm128_h8

model:
  name: PatchTST
  d_model: 128
  d_ff: 256
  n_heads: 8
  e_layers: 3
  d_layers: 1
  factor: 3
  dropout: 0.1

data:
  name: ETTh1
  root_path: ./dataset/ETDataset/ETT-small/
  data_path: ETTh1.csv
  features: M
  target: OT
  freq: h
  seq_len: 336
  label_len: 48
  pred_len: 96
  enc_in: 7
  dec_in: 7
  c_out: 7

training:
  batch_size: 32
  max_epochs: 10
  best_epoch: 7
  patience: 3
  learning_rate: 0.0001
  loss: MSE
  lradj: type1
  optimizer: Adam
  use_gpu: true

results:
  best_val_loss: 0.6734824
  test_mse: 0.37254568934440613
  test_mae: 0.3982141613960266

notes:
  description: baseline_b4
  checkpoint_selected_by: validation_loss
""".strip()

b4_config_path = (
    CONFIG_DIR
    / "B4_patchtst_etth1_336_dm128_h8.yaml"
)

b4_config_path.write_text(
    b4_config,
    encoding="utf-8",
)

print("B4 config kaydedildi:")
print(b4_config_path)

B4 config kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/configs/B4_patchtst_etth1_336_dm128_h8.yaml

In [ ]:
from pathlib import Path

checkpoint_root = Path(
    "/content/Time-Series-Library/checkpoints"
)

b4_matches = [
    path
    for path in checkpoint_root.iterdir()
    if "ETTh1_336_96_dm128_h8" in path.name
]

for path in b4_matches:
    print(path)

/content/Time-Series-Library/checkpoints/long_term_forecast_ETTh1_336_96_dm128_h8_PatchTST_ETTh1_ftM_sl336_ll48_pl96_dm128_nh8_el3_dl1_df256_expand2_dc4_fc3_ebtimeF_dtTrue_baseline_b4_0

In [ ]:
import shutil

CHECKPOINT_DIR = PROJECT_DIR / "checkpoints"
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

if len(b4_matches) != 1:
    raise RuntimeError(
        f"1 B4 checkpoint bekleniyordu, {len(b4_matches)} bulundu."
    )

source_b4 = b4_matches[0]

target_b4 = (
    CHECKPOINT_DIR
    / "B4_patchtst_etth1_336_dm128_h8"
)

if target_b4.exists():
    shutil.rmtree(target_b4)

shutil.copytree(
    source_b4,
    target_b4,
)

print("B4 checkpoint kaydedildi:")
print(target_b4)

B4 checkpoint kaydedildi:
/content/drive/MyDrive/BIL401_Regime_Head_Pruning/checkpoints/B4_patchtst_etth1_336_dm128_h8

In [ ]:
import pandas as pd
from pathlib import Path

PROJECT_DIR = Path(
    "/content/drive/MyDrive/BIL401_Regime_Head_Pruning"
)

results_path = PROJECT_DIR / "results" / "baseline_experiments.csv"

results_df = pd.read_csv(results_path)

results_df["selected_for_pruning"] = False

results_df.loc[
    results_df["experiment_id"]
    == "B4_patchtst_etth1_336_dm128_h8",
    "selected_for_pruning"
] = True

results_df.to_csv(results_path, index=False)

display(results_df)

,experiment_id,model,dataset,seq_len,label_len,pred_len,d_model,d_ff,n_heads,e_layers,...,max_epochs,best_epoch,patience,learning_rate,best_val_loss,test_mse,test_mae,status,rerun_confirmed,selected_for_pruning
0,B0_patchtst_etth1_336_dm128_h4,PatchTST,ETTh1,336,48,96,128,256,4,3,...,10,7,3,0.0001,0.673162,0.373876,0.398880,completed,NaN,False
1,B1_patchtst_etth1_512_dm128_h16,PatchTST,ETTh1,512,48,96,128,256,16,3,...,20,6,5,0.0001,0.738233,0.376424,0.405316,completed,NaN,False
2,B2_patchtst_etth1_512_dm256_h16,PatchTST,ETTh1,512,48,96,256,512,16,3,...,20,5,5,0.0001,0.781129,0.394739,0.423382,completed,True,False
3,B3_patchtst_etth1_336_dm128_h16,PatchTST,ETTh1,336,48,96,128,256,16,3,...,10,8,3,0.0001,0.678088,0.373510,0.399407,completed,NaN,False
4,B4_patchtst_etth1_336_dm128_h8,PatchTST,ETTh1,336,48,96,128,256,8,3,...,10,7,3,0.0001,0.673482,0.372546,0.398214,completed,NaN,True

Warning: Total number of columns (21) exceeds max_columns (20) limiting to first (20) columns.